/**
 * Shunya Competition Events — The 6 core data objects.
 * Each event is rendered 3× (18 DOM nodes) for seamless infinite looping.
 * Content is accessed via: events[nodeIndex % EVENTS.length]
 */

export const EVENTS = [
  {
    id: 0,
    title: "Zero Day Apocalypse",
    tag: "Prompt Engineering + AI Adversarial Thinking",
    description: "An interactive AI-adversarial event where participants compete against an LLM. Battle to crack secret passwords using strategic prompt engineering. The difficulty increases with each round, simulating the adversarial edge between human intelligence and AI systems.",
    accent: "#FF2D55", // Pulsar Red
    date: "11th September",
    venue: "APJ",
  },
  {
    id: 1,
    title: "24-Hour Devlympics",
    tag: "Cybersecurity + Rapid Prototyping",
    description: "A 24-hour cybersecurity sprint. Build a functional security or threat-detection prototype from scratch addressing real-world vulnerabilities. Pitch your final security solution to a judging panel after continuous mentorship and rapid prototyping.",
    accent: "#FFD60A", // Solar Flare
    date: "12th–13th September",
    venue: "Smart Block",
  },
  {
    id: 2,
    title: "Autopilot",
    tag: "Agentic AI + Tool Use + Optimization",
    description: "A 6-hour Agentic AI challenge. Create autonomous AI agents capable of solving task-specific problems using tools in a controlled platform. Judged on accuracy, latency, tool usage, and total cost.",
    accent: "#00C2FF", // Ion Blue
    date: "12th September",
    venue: "APJ",
  },
  {
    id: 3,
    title: "Flow in Flux 2026",
    tag: "Design Thinking + Creativity",
    description: "A 2-day overnight design competition focused on solving real-world challenges across Branding, UI/UX, Product Design, Game Design, and AI-Assisted Design. Allocate statements, sprint, and present your project to the jury.",
    accent: "#BF5AF2", // Nebula Violet
    date: "11th–12th September",
    venue: "Smart Block",
  },
  {
    id: 4,
    title: "The Hallucination Hunt",
    tag: "LLM Code Review + Debugging",
    description: "A timed, leaderboard-style bug hunt. Audit code snippets generated by various LLMs, identify subtle logic errors, detect hallucinated API calls, and fix the generated code. Reverses the usual 'writing with AI' workflow.",
    accent: "#32D74B", // Plasma Green
    date: "11th September",
    venue: "Mini Audi",
  },
  {
    id: 5,
    title: "AI Case-a-thon",
    tag: "AI Strategy + Consulting",
    description: "A high-intensity consulting case competition focused on applying AI to complex real-world socio-economic problems. Determine whether and how AI technology should be adopted to scale social impact while balancing sustainability and ethics.",
    accent: "#FF9F0A", // Quasar Amber
    date: "12th September",
    venue: "Mini Audi",
  },
  {
    id: 6,
    title: "The Glitch Race",
    tag: "Design + Innovation + Rapid Solving",
    description: "A 2-day overnight design competition solving real-world design challenges across multiple creative domains including UI/UX, Game Design, and Packaging. Rapid creative problem solving from problem allocation to jury evaluation.",
    accent: "#FF00FF", // Neon Magenta
    date: "11th September",
    venue: "Mini Audi",
  },
  {
    id: 7,
    title: "Biome Orbit",
    tag: "Immersive Puzzle Quest + Nature + Tech",
    description: "A sequential puzzle quest through four zones representing different natural biomes (Forest, Ocean, Atmosphere, Orbit). Solve nature-and-technology-inspired puzzles to unlock the final launch code in this immersive, timed challenge.",
    accent: "#00FFFF", // Electric Cyan
    date: "12th September",
    venue: "Mini Audi",
  },
];
