/**
 * Shunya Competition Events — The 8 core data objects.
 * Each event is rendered 3× (24 DOM nodes) for seamless infinite looping.
 * Content is accessed via: events[nodeIndex % EVENTS.length]
 */

export const EVENTS = [
  // DAY 1 - 11th September
  {
    id: 0,
    title: "Zero Day Apocalypse",
    tag: "Prompt Engineering + AI Adversarial Thinking",
    description: "An interactive AI-adversarial event where participants compete against an LLM. Battle to crack secret passwords using strategic prompt engineering. The difficulty increases with each round, simulating the adversarial edge between human intelligence and AI systems.",
    accent: "#FF003C", // Crimson Red
    date: "16th September",
    venue: "APJ",
    registerUrl: "https://unstop.com/hackathons/zero-day-apocalypse-shunya-2026-netaji-subhas-university-of-technology-nsut-delhi-1764669?lb=YnzLtiB5&utm_medium=Share&utm_source=gdscnsu34405&utm_campaign=Online_coding_challenge",
    registrationDeadline: "16 Oct",
  },
  {
    id: 1,
    title: "Flow in Flux 2026",
    tag: "Design Thinking + Creativity",
    description: "A 2-day overnight design competition focused on solving real-world challenges across Branding, UI/UX, Product Design, Game Design, and AI-Assisted Design. Allocate statements, sprint, and present your project to the jury.",
    accent: "#8A2BE2", // Deep Violet
    date: "17th - 18th September",
    venue: "Smart Block",
    registerUrl: "https://unstop.com/competitions/flow-in-flux-shunya-2026-netaji-subhas-university-of-technology-nsut-delhi-1764670?lb=YnzLtiB5&utm_medium=Share&utm_source=gdscnsu34405&utm_campaign=Events",
    registrationDeadline: "14 Oct",
  },
  {
    id: 2,
    title: "The Hallucination Hunt",
    tag: "LLM Code Review + Debugging",
    description: "A timed, leaderboard-style bug hunt. Audit code snippets generated by various LLMs, identify subtle logic errors, detect hallucinated API calls, and fix the generated code. Reverses the usual 'writing with AI' workflow.",
    accent: "#39FF14", // Toxic Lime
    date: "Date : TBA",
    venue: "Mini Audi",
    registerUrl: "",
    registrationDeadline: "TBA",
  },
  {
    id: 3,
    title: "The Glitch Race",
    tag: "Design + Innovation + Rapid Solving",
    description: "A 2-day overnight design competition solving real-world design challenges across multiple creative domains including UI/UX, Game Design, and Packaging. Rapid creative problem solving from problem allocation to jury evaluation.",
    accent: "#FF00FF", // Hot Magenta
    date: "Date : TBA",
    venue: "Mini Audi",
    registerUrl: "",
    registrationDeadline: "TBA",
  },
  
  // DAY 2 - 12th September
  {
    id: 4,
    title: "Autopilot",
    tag: "Agentic AI + Tool Use + Optimization",
    description: "A 6-hour Agentic AI challenge. Create autonomous AI agents capable of solving task-specific problems using tools in a controlled platform. Judged on accuracy, latency, tool usage, and total cost.",
    accent: "#0066FF", // Electric Blue
    date: "17th September",
    venue: "APJ",
    registerUrl: "https://unstop.com/hackathons/autopilot-shunya-2026-netaji-subhas-university-of-technology-nsut-delhi-1764668?lb=YnzLtiB5&utm_medium=Share&utm_source=gdscnsu34405&utm_campaign=Online_coding_challenge",
    registrationDeadline: "16 Oct",
  },
  {
    id: 5,
    title: "AI Case-a-thon",
    tag: "AI Strategy + Consulting",
    description: "A high-intensity consulting case competition focused on applying AI to complex real-world socio-economic problems. Determine whether and how AI technology should be adopted to scale social impact while balancing sustainability and ethics.",
    accent: "#FF6600", // Neon Orange
    date: "Date : TBA",
    venue: "Mini Audi",
    registerUrl: "",
    registrationDeadline: "TBA",
  },
  {
    id: 6,
    title: "Biome Orbit",
    tag: "Immersive Puzzle Quest + Nature + Tech",
    description: "A sequential puzzle quest through four zones representing different natural biomes (Forest, Ocean, Atmosphere, Orbit). Solve nature-and-technology-inspired puzzles to unlock the final launch code in this immersive, timed challenge.",
    accent: "#00FFFF", // Pure Cyan
    date: "Date : TBA",
    venue: "Mini Audi",
    registerUrl: "",
    registrationDeadline: "TBA",
  },
  {
    id: 7,
    title: "24-Hour Devlympics",
    tag: "Cybersecurity + Rapid Prototyping",
    description: "A 24-hour cybersecurity sprint. Build a functional security or threat-detection prototype from scratch addressing real-world vulnerabilities. Pitch your final security solution to a judging panel after continuous mentorship and rapid prototyping.",
    accent: "#FFE600", // Cyber Yellow
    date: "17th - 18th September",
    venue: "Smart Block",
    registerUrl: "https://unstop.com/hackathons/devlympics-shunya-2026-netaji-subhas-university-of-technology-nsut-delhi-1764596?lb=YnzLtiB5&utm_medium=Share&utm_source=gdscnsu34405&utm_campaign=Online_coding_challenge",
    registrationDeadline: "15 Oct",
  }
];
