/**
 * Shunya Competition Events — The 8 core data objects.
 * Each event is rendered 3× (24 DOM nodes) for seamless infinite looping.
 * Content is accessed via: events[nodeIndex % EVENTS.length]
 */

export const EVENTS = [
  // DAY 1 - 11th September
  {
    id: 0,
    title: "Zero Day Apocalypse",
    tag: "Prompt Engineering + AI Adversarial Thinking",
    description: "An interactive AI-adversarial event where participants compete against an LLM. Battle to crack secret passwords using strategic prompt engineering. The difficulty increases with each round, simulating the adversarial edge between human intelligence and AI systems.",
    accent: "#FF003C", // Crimson Red
    date: "16th October | 10:00 AM",
    venue: "APJ 11",
    registerUrl: "https://unstop.com/hackathons/zero-day-apocalypse-shunya-2026-netaji-subhas-university-of-technology-nsut-delhi-1764669?lb=YnzLtiB5&utm_medium=Share&utm_source=gdscnsu34405&utm_campaign=Online_coding_challenge",
    registrationDeadline: "16 Oct",
  },
  {
    id: 1,
    title: "Flow in Flux 2026",
    tag: "Design Thinking + Creativity",
    description: "A 2-day overnight design competition focused on solving real-world challenges across Branding, UI/UX, Product Design, Game Design, and AI-Assisted Design. Allocate statements, sprint, and present your project to the jury.",
    accent: "#8A2BE2", // Deep Violet
    date: "17th - 18th October | 10:00 AM",
    venue: "Round 1, APJ",
    registerUrl: "https://unstop.com/competitions/flow-in-flux-shunya-2026-netaji-subhas-university-of-technology-nsut-delhi-1764670?lb=YnzLtiB5&utm_medium=Share&utm_source=gdscnsu34405&utm_campaign=Events",
    registrationDeadline: "14 Oct",
  },
  {
    id: 2,
    title: "The Hallucination Hunt",
    tag: "LLM Code Review + Debugging",
    description: "A timed, leaderboard-style bug hunt. Audit code snippets generated by various LLMs, identify subtle logic errors, detect hallucinated API calls, and fix the generated code. Reverses the usual 'writing with AI' workflow.",
    accent: "#00FF66", // Neon Green
    date: "TBA | 10:00 AM",
    venue: "Mini Audi",
    registerUrl: "",
    registrationDeadline: "TBA",
  },
  {
    id: 3,
    title: "Tech Mafia",
    tag: "Social Deduction + Debugging + AI Prompting",
    description: "A team-based technical social deduction game. Teams of 6 have hidden Mafia members secretly sabotaging progress. Survive 2 rounds of coding and AI prompting challenges, identify the Mafia in a live debate, then battle individually in The Final Hack for the top 3 spots.",
    accent: "#FF0080", // Neon Crimson-Pink
    date: "17th October | 10:00 AM",
    venue: "APJ",
    registerUrl: "",
    registrationDeadline: "TBA",
  },
  
  // DAY 2 - 12th September
  {
    id: 4,
    title: "Autopilot",
    tag: "Agentic AI + Tool Use + Optimization",
    description: "A 6-hour Agentic AI challenge. Create autonomous AI agents capable of solving task-specific problems using tools in a controlled platform. Judged on accuracy, latency, tool usage, and total cost.",
    accent: "#0066FF", // Electric Blue
    date: "17th October | 10:00 AM",
    venue: "APJ 11",
    registerUrl: "https://unstop.com/hackathons/autopilot-shunya-2026-netaji-subhas-university-of-technology-nsut-delhi-1764668?lb=YnzLtiB5&utm_medium=Share&utm_source=gdscnsu34405&utm_campaign=Online_coding_challenge",
    registrationDeadline: "16 Oct",
  },
  {
    id: 5,
    title: "REDLINE",
    tag: "Autonomous AI Battle + ML Strategy",
    description: "A live AI-versus-AI Pokémon-style battle. Build a 3-Pokémon team, then code an autonomous ML agent to fight for you. No human control during battles. The AI receives the game state, selects its move, and the battle engine executes it on a live animated display.",
    accent: "#00FFFF", // Pure Cyan
    date: "17th October | 10:00 AM",
    venue: "Mini Audi",
    registerUrl: "https://unstop.com/o/SaoZzvV?lb=I1O9Szp&utm_medium=Share&utm_source=aresnsit&utm_campaign=Online_coding_challenge",
    registrationDeadline: "TBA",
  },
  {
    id: 6,
    title: "Space & Beyond Ideathon",
    tag: "Space Tech + Innovation + Future Ideas",
    description: "An open ideation platform by Team Kalpana. Explore themes of Beyond Earth, Smart World, or Future Without Limits. Identify a real-world problem, develop an innovative concept, build a prototype or presentation, and demonstrate its potential impact to the jury.",
    accent: "#FF6B35", // Cosmic Orange
    date: "17th October | 10:00 AM",
    venue: "APJ",
    registerUrl: "https://unstop.com/o/5mKA9Iv?lb=QXWbNZ5&utm_medium=Share&utm_source=online_coding_challenge&utm_campaign=Kalpanaczrml8757",
    registrationDeadline: "TBA",
  },
  {
    id: 7,
    title: "24-Hour Devlympics",
    tag: "Cybersecurity + Rapid Prototyping",
    description: "A 24-hour cybersecurity sprint. Build a functional security or threat-detection prototype from scratch addressing real-world vulnerabilities. Pitch your final security solution to a judging panel after continuous mentorship and rapid prototyping.",
    accent: "#FFE600", // Cyber Yellow
    date: "17th - 18th October | 10:00 AM",
    venue: "Smart Block",
    registerUrl: "https://unstop.com/hackathons/devlympics-shunya-2026-netaji-subhas-university-of-technology-nsut-delhi-1764596?lb=YnzLtiB5&utm_medium=Share&utm_source=gdscnsu34405&utm_campaign=Online_coding_challenge",
    registrationDeadline: "15 Oct",
  }
];
